FROM alpine:3.10

RUN apk add --update --no-cache \
    libgcc libstdc++ libx11 glib libxrender libxext libintl \
    ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family

COPY --from=jrm0/alpine-wkhtmltopdf-builder:0.12.5 \
    /bin/wkhtmltopdf /bin/wkhtmltopdf

ENTRYPOINT ["wkhtmltopdf"]
